main: org.modularsoft.MobHunt.MobHuntMain
name: MobHunt
description: Hunt as many mobs overall, or of a unique mob type.
version: ${project.version}
authors: [ModularSoft]
api-version: 1.21
softdepend:
  - DecentHolograms

commands:
  mobstats:
    description: Shows a breakdown of the mobs you killed, or another player if you are an Admin.
    usage: /mobstats [player]
  mobclear:
    description: Clear all mobs from yourself or another player.
    usage: /mobclear [player]
  mobleaderboard:
    description: Show the Top 5 Mob Hunters overall or of a specific mob.
    usage: /mobleaderboard [mob]
    aliases: [lb, leaderboard]
  mobhelp:
    description: Helps the player know how to play Mob Hunt.
    usage: /mobhelp
    aliases: [howtoplay]
  mobscoreboard:
    description: Toggle the Mob Hunt sidebar scoreboard on or off.
    usage: /mobscoreboard [on|off]
    aliases: [mhsb, mobsb]
  mh:
    description: Toggle Mob Hunt features such as the sidebar and point notifications.
    usage: /mh toggle <scoreboard|notifications> [on|off]
    aliases: [mhtoggle]
