main: com.modularenigma.MobHunt.MobHuntMain
name: MobHunt
description: Hunt as many mobs overall, or of a unique mob type.
version: ${project.version}
authors: [Ben Robson, ModularEnigma]
api-version: 1.18

commands:
  mobs:
    description: Grab the amount of eggs you have.
    usage: /eggs
  clearmobs:
    description: Clear all mobs from yourself, all or a specific mob.
    usage: /clearmobs [all/type] [mobtype]
  leaderboardmobs:
    description: Show the Top 5 Mob Hunters of overall or a specific mob.
    usage: /leaderboardmobs [all/type]
    aliases: [lb, leaderboard]