main: com.modularenigma.MobHunt.MobHuntMain
name: MobHunt
description: Hunt as many mobs overall, or of a unique mob type.
version: ${project.version}
authors: [Ben Robson, ModularEnigma]
api-version: 1.18

commands:
  mobstats:
    description: Shows a breakdown of the mobs you've killed.
    usage: /mobstats
  mobclear:
    description: Clear all mobs from yourself, all or a specific mob.
    usage: /mobclear [all/type] [mobtype]
  mobleaderboard:
    description: Show the Top 5 Mob Hunters of overall or a specific mob.
    usage: /mobleaderboard [all/type]
    aliases: [lb, leaderboard]